source: site
# 主题
theme: jekyll-theme-minimal
# 标题
title: Sundayplay's homepage
# 描述
description: Bookmark this to keep an eye on my project updates!
# 时区
timezone: Asia/Shanghai
# markdown格式
markdown: GFM
google_analytics:
show_downloads: true
logo: /assets/img/logo.png
github:
  zip_url: http://example.com/downloadzip.zip
  tar_url: http://example.com/downloadtar.zip
